/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import { useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import { addBlog, getAnime, getMoreAnime } from "../src/blog/blogSlice";
import {
  decrement,
  increment,
  incrementByAmount,
} from "../src/counter/counterSlice";
import getStore from "../src/store";

import styles from "../styles/Home.module.css";

function Home() {
  const dispatch = useDispatch();
  const { counter } = useSelector((state) => state);
  const { anime, next } = useSelector((state) => state.blog);
  const [entry, setEntry] = useState("");
  const numberEntry = Number(entry) || 0;
  return (
    <div className={styles.main}>
      <Head>
        <title>Pokemon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.container}>
        <button onClick={() => dispatch(decrement())}>-</button>
        <p>{counter.value}</p>
        <button onClick={() => dispatch(increment())}>+</button>
        <input
          type="text"
          value={entry}
          onChange={(e) => setEntry(e.target.value)}
        />
        <button onClick={() => dispatch(incrementByAmount(numberEntry))}>
          ADD
        </button>
        {anime.map((p) => (
          <div key={p.id} className={styles.image}>
            <img alt={p.title} src={p.image} />
            <h2>{p.title}</h2>
            <p>{p.body}</p>
          </div>
        ))}
        <button onClick={() => dispatch(getMoreAnime(next))}>Next Page</button>
      </div>
    </div>
  );
}

export async function getServerSideProps() {
  const store = getStore();
  await store.dispatch(getAnime());
  return {
    props: {
      initialState: store.getState(),
    },
  };
}

export default Home;
